apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
        import /etc/coredns/custom/*.override
    }
    import /etc/coredns/custom/*.server
  NodeHosts: |
    172.19.0.1 host.k3d.internal
    172.19.0.4 k3d-platform-agent-1
    172.19.0.3 k3d-platform-agent-0
    172.19.0.2 k3d-platform-server-0
    172.19.0.5 k3d-platform-serverlb
kind: ConfigMap
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4xQwYrUQBD9labOSTudzGyyDR5kL4Lo0dNeKunKpE2nKnTXjizD/rvEQRFkdW+veK8e770r4Ba/Ui5RGDxcHFQQUBH8FR4k0xQTgQfrT625PrIxxlDOkssNz4RJ5xvOhOH5BpengTKTUjFjeipK2SaBCr5IoI9StIAH1zXW3duDdWaWonZpg42slBnTI/9mj2ZpQ70l1EnyWuOZWGv3UwAvFSyRA3h4EJ7i+TNuUMFKir8qILMoahQu+ynDNxq1kNocxY6omshGeRd3D6he5eU7U67PlwU8LG35g7m4ynyKHN5/CEH4vxaM6z7nKJkClzfJy4bj/rNvWpfnorTuxRMOlP5ZasYyg4dhpKZvm/u+d647tnho+zscTu4wNdNdR1N3bI6H8dTtpn/FezXAy48AAAD//8Glviw5AgAA
    objectset.rio.cattle.io/id: ""
    objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
    objectset.rio.cattle.io/owner-name: coredns
    objectset.rio.cattle.io/owner-namespace: kube-system
  creationTimestamp: "2026-04-08T10:13:48Z"
  labels:
    objectset.rio.cattle.io/hash: bce283298811743a0386ab510f2f67ef74240c57
  name: coredns
  namespace: kube-system
  resourceVersion: "529"
  uid: 62294024-1e75-4b5c-8aad-ee14daa844aa
