apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis.yaml
  - api.yaml
  - api-alerts.yaml
  - worker.yaml
  - frontend.yaml
  - servicemonitor-api.yaml

namespace: default
