apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-metrics
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: api
  endpoints:
  - port: "http"  # matches the Service port name
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default  # adjust if your Service is in a different namespace
